const $=s=>document.querySelector(s),engine=FormEngine,ids=['name','identity','oldNumber','newNumber','donor','commencement','hours','room','floor','block','building','street','district','region','correctName','sex','ownerName','ownerIdentity','broadbandAction','installationDate','installationTime','effectiveDate'];
let task='cover';
let transfereeStrokes=[];
let signatureImage=null,transfereeImage=null,signatureUploadVersion=0,transfereeUploadVersion=0,signatureLoading=false,transfereeLoading=false;
let strokes=[],activeStroke=null,pointerId=null,images={},pages={},selectedPage='cos',ready=false,timer=null,dirty=false,modalMode='preview';
const sig=$('#signature'),sc=sig.getContext('2d');const pageLabels={cos:'Change of Service Application',mnp:'Mobile Number Portability Application',terms:'MNP · Terms & Conditions'};
function data(){const d=Object.fromEntries(ids.map(id=>[id,$('#'+id).value.trim()]));d.prepaid=$('input[name="prepaid"]:checked')?.value||'';d.task=task;d.transfereeStrokes=transfereeStrokes;d.signatureImage=signatureImage;d.transfereeImage=transfereeImage;return d;}
function update(){const d=data();$('#today').textContent=engine.dateText(engine.hongKongToday());$('#old-display').textContent=task==='broadband'?'寛頻帳戶號碼':['senior','address','name','owner'].includes(task)?'客戶號碼':task==='date'?'轉台號碼':d.oldNumber||'原有號碼';$('#new-display').textContent=d.newNumber||(task!=='cover'?'電話號碼':'新號碼');$('#prepaid-note').textContent=d.prepaid==='yes'?'MNP：勾選儲值卡、圈選 Y，並在姓名前加入 PREPAID SIM。':d.prepaid==='no'?'MNP：圈選 N，不加姓名前綴。':(task==='date'?'請選擇此號碼目前使用的服務類型。':'請選擇新號碼目前使用的服務類型。');if(!ready)return;const today=engine.hongKongToday();if(task!=='date')pages.cos=engine.render('cos',d,strokes,images,()=>document.createElement('canvas'),today);else delete pages.cos;if(!['senior','address','broadband'].includes(task))pages.mnp=engine.render('mnp',d,strokes,images,()=>document.createElement('canvas'),today);else delete pages.mnp;if(!pages.terms)pages.terms=engine.render('terms',d,[],images,()=>document.createElement('canvas'),today);showPage();}
function showPage(){if(!ready)return;const c=$('#preview'),source=pages[selectedPage];c.width=source.width;c.height=source.height;c.getContext('2d').drawImage(source,0,0);$('#page-label').textContent=pageLabels[selectedPage];}
function changed(){dirty=true;$('#status').textContent='草稿';$('#error').textContent='';clearTimeout(timer);timer=setTimeout(update,90);}
ids.forEach(id=>$('#'+id).addEventListener('input',()=>{$('#'+id).setCustomValidity('');if(id==='newNumber'||id==='oldNumber')$('#newNumber').setCustomValidity('');changed();}));document.querySelectorAll('input[name="prepaid"]').forEach(i=>i.addEventListener('change',changed));
const tabs=[...document.querySelectorAll('[data-page]')];function selectTab(b){selectedPage=b.dataset.page;tabs.forEach(t=>{const on=t===b;t.classList.toggle('active',on);t.setAttribute('aria-selected',on);t.tabIndex=on?0:-1;});$('#preview-panel').setAttribute('aria-labelledby',b.id);showPage();}tabs.forEach((b,i)=>{b.tabIndex=i? -1:0;b.onclick=()=>selectTab(b);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const visible=tabs.filter(t=>!t.hidden),index=visible.indexOf(b);const n=e.key==='Home'?0:e.key==='End'?visible.length-1:(index+(e.key==='ArrowRight'?1:visible.length-1))%visible.length;selectTab(visible[n]);visible[n].focus();}};});
function drawSignature(){sc.clearRect(0,0,sig.width,sig.height);sc.strokeStyle='#162c39';sc.lineWidth=3.5;sc.lineCap='round';sc.lineJoin='round';for(const stroke of strokes){if(!stroke.length)continue;sc.beginPath();stroke.forEach((p,i)=>i?sc.lineTo(p.x,p.y):sc.moveTo(p.x,p.y));sc.stroke();}if(signatureImage)engine.drawSignatureImage(sc,signatureImage,0,0,sig.width,sig.height);$('#signature-placeholder').hidden=!!signatureImage||strokes.some(s=>s.length>1);$('#undo').disabled=!signatureImage&&strokes.length===0;$('#clear').disabled=!signatureImage&&strokes.length===0;}
function point(e){const r=sig.getBoundingClientRect();return {x:Math.max(0,Math.min(1000,(e.clientX-r.left)/r.width*1000)),y:Math.max(0,Math.min(300,(e.clientY-r.top)/r.height*300))};}
sig.addEventListener('pointerdown',e=>{if(pointerId!==null||e.button>0||signatureImage||signatureLoading)return;e.preventDefault();pointerId=e.pointerId;sig.setPointerCapture(pointerId);activeStroke=[point(e)];strokes.push(activeStroke);drawSignature();});sig.addEventListener('pointermove',e=>{if(pointerId!==e.pointerId||!activeStroke)return;e.preventDefault();activeStroke.push(point(e));drawSignature();});function endStroke(e){if(e.pointerId!==pointerId)return;if(activeStroke?.length<2)strokes.pop();activeStroke=null;pointerId=null;drawSignature();changed();}sig.addEventListener('pointerup',endStroke);sig.addEventListener('pointercancel',endStroke);sig.addEventListener('lostpointercapture',endStroke);
$('#undo').onclick=()=>{signatureUploadVersion++;signatureLoading=false;if(signatureImage){signatureImage=null;$('#signature-upload').value='';}else strokes.pop();drawSignature();changed();};$('#clear').onclick=()=>{signatureUploadVersion++;signatureLoading=false;signatureImage=null;$('#signature-upload').value='';strokes=[];drawSignature();changed();};
function valid(){if(signatureLoading||(task==='owner'&&transfereeLoading)){$('#error').textContent='簽名圖片載入中，請稍候。';return false;}if(!ready){$('#error').textContent='表格尚未載入，請稍候。';return false;}const d=data();for(const id of (task==='owner'?['name','identity','ownerName','ownerIdentity','donor']:task==='name'?['name','correctName','sex','identity','donor']:task==='address'?['name','identity','district','region']:['senior','broadband'].includes(task)?['name','identity']:['name','identity','donor']))$('#'+id).setCustomValidity(d[id]?'':'請填寫此欄位。');$('#newNumber').setCustomValidity(task==='cover'&&d.oldNumber&&d.oldNumber===d.newNumber?'原有號碼與新號碼不可相同。':'');if(task==='broadband'&&d.broadbandAction==='install')$('#installationTime').setCustomValidity(d.installationTime?'':'請填寫安裝時間或時段。');if(!$('#application').reportValidity())return false;if(task==='address'&&!d.building&&!d.street){$('#error').textContent='請填寫大廈／屋苑或街道地址。';$('#building').focus();return false;}if(!signatureImage&&!strokes.some(s=>s.length>2)){$('#error').textContent='請先在簽名區完成客戶簽署。';sig.focus();sig.scrollIntoView({behavior:'smooth',block:'center'});return false;}if(task==='owner'&&!transfereeImage&&!transfereeStrokes.some(s=>s.length>2)){$('#error').textContent='請完成新號碼持有人簽署。';$('#signature-transferee').focus();$('#signature-transferee').scrollIntoView({behavior:'smooth',block:'center'});return false;}return true;}
function openPreview(isReview){if(isReview&&!valid())return;if(!ready)return;clearTimeout(timer);update();modalMode=isReview?'review':'preview';const d=data();$('#review-info').textContent=isReview?`${task==='owner'?'原持有人：'+d.name+' → 新持有人：'+d.ownerName:task==='name'?d.name+' → '+d.correctName:d.name} · ${task!=='cover'?d.newNumber:d.oldNumber+' → '+d.newNumber} · ${task==='broadband'?engine.broadbandRemark(d):task==='address'?'更改地址 · '+[d.room,d.floor,d.block,d.building,d.street,d.district,d.region].filter(Boolean).join(' / '):task==='senior'?'長者申請郵寄帳單 · '+engine.dateText(engine.hongKongToday()):engine.dateText(d.commencement)+' '+(d.hours==='night'?'0100–0400':'1200–1400')+' · '+(d.prepaid==='yes'?'儲值卡':'月費服務')}`:'預覽目前填寫內容。請完成必填資料及客戶簽署後再產生文件。';$('#review-pages').replaceChildren();const kinds=isReview?engine.documentKinds(task):[selectedPage];for(const kind of kinds){const fig=document.createElement('figure'),caption=document.createElement('figcaption'),img=document.createElement('img');caption.textContent=pageLabels[kind];img.src=pages[kind].toDataURL('image/png');img.alt=pageLabels[kind];fig.append(caption,img);$('#review-pages').append(fig);}$('.downloads').hidden=!isReview;$('#download-status').textContent='';$('#review-dialog').showModal();$('#review-dialog').scrollTop=0;if(isReview)$('#status').textContent='待核對';}
$('#application').onsubmit=e=>{e.preventDefault();openPreview(true);};$('#zoom').onclick=()=>openPreview(false);$('#close-dialog').onclick=()=>$('#review-dialog').close();
async function download(which){if(!valid()){$('#review-dialog').close();return;}try{if(!await recordGeneration(task))return;update();const groups=engine.downloadGroups(task,which,data());const downloads=groups.map(group=>({filename:group.filename,blob:engine.pdf(group.kinds.map(k=>pages[k]))}));for(const file of downloads){const url=URL.createObjectURL(file.blob),a=document.createElement('a');a.href=url;a.download=file.filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}$('#download-status').textContent=downloads.length>1?'已分別產生 COS 及 MNP PDF。如瀏覽器阻止第二個下載，請允許多個檔案下載，或使用下方個別下載按鈕。':'已產生 PDF。如瀏覽器開啟預覽，請使用分享選單儲存檔案。';$('#status').textContent='已產生';}catch(e){$('#download-status').textContent='未能產生 PDF，請再試一次。';}}

$('#download-all').onclick=()=>download('all');$('#download-cos').onclick=()=>download('cos');$('#download-mnp').onclick=()=>download('mnp');$('#reset').onclick=()=>{if(dirty&&!confirm('清除全部資料及簽名，開始新申請？'))return;$('#application').reset();ids.forEach(id=>$('#'+id).setCustomValidity(''));strokes=[];transfereeStrokes=[];signatureImage=null;transfereeImage=null;signatureUploadVersion++;transfereeUploadVersion++;signatureLoading=false;transfereeLoading=false;syncBroadband();drawTransferee();drawSignature();dirty=false;$('#status').textContent='草稿';$('#error').textContent='';update();};
async function load(){try{const loaded=await Promise.all([['cos','template.png'],['mnp','mnp-1.png'],['terms','mnp-2.png'],['seniorRemark','senior-remark.png'],['bbCancel','bb-cancel.png'],['bbInstall','bb-install.png'],['bbEffective','bb-effective.png'],['bbEffectiveLabel','bb-effective-label.png']].map(([key,src])=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve([key,img]);img.onerror=reject;img.src=src;})));images=Object.fromEntries(loaded);ready=true;$('#review').disabled=false;$('#zoom').disabled=false;$('#status').textContent='草稿';update();}catch(e){$('#status').textContent='載入失敗';$('#error').textContent='無法載入表格，請重新整理頁面再試。';}}

function setTask(next){
 task=next;const dateOnly=task==='date',senior=task==='senior',address=task==='address',correction=task==='name',ownership=task==='owner',broadband=task==='broadband',cosOnly=senior||address||broadband,singleNumber=task!=='cover';clearTimeout(timer);
 document.querySelectorAll('[data-task]').forEach(b=>{const active=b.dataset.task===task;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});
 const copy={
 'task-number':dateOnly?'服務申請 / 02':'服務申請 / 01',
 'task-title':dateOnly?'更改轉台日期':'冚號碼',
 'task-description':dateOnly?'填寫新的轉台日期及時段，準備 MNP 申請表。':'輸入一次資料，同步填妥 COS 及 MNP 表格。',
 'form-total':dateOnly?'1':'2','page-total':dateOnly?'共 2 頁，包含 MNP 條款':'共 3 頁，包含 MNP 條款',
 'name-hint':dateOnly?'與現有登記資料一致，填入 MNP 的 Name in English。':'與現有登記資料一致。姓名會同步填入兩份表格。',
 'mobile-label':dateOnly?'電話號碼 Mobile Number':'新號碼 To','mobile-hint':dateOnly?'需要更改轉台日期的電話號碼。':'COS：To · MNP：Mobile Number',
 'date-label':dateOnly?'新的轉台日期':'生效 / 轉台日期','date-hint':dateOnly?'填入 MNP 的 Requested Cut-over Time。':'兩份表格共用此日期。',
 'prepaid-label':dateOnly?'此號碼是否儲值卡？':'新號碼是否儲值卡？',
 'signature-hint':dateOnly?'簽名會放入 MNP 表格左下方的客戶簽署位置。':'同一簽名會放入兩份表格的客戶簽署位置。',
 'preview-hint':dateOnly?'下載前請核對電話號碼、新轉台日期、時段及簽名。':'文件會包含客戶資料、轉台安排及簽名。下載前請核對兩份申請表。',
 'footer-task':dateOnly?'更改轉台日期 · MNP':'冚號碼 · COS + MNP',
 'download-all':dateOnly?'下載 MNP（2 頁 PDF，含條款）':'一鍵下載 COS 及 MNP（兩個 PDF）'
 };if(cosOnly)Object.assign(copy,{'task-number':'服務申請 / 03','task-title':'長者申請郵寄帳單','task-description':'填妥客戶資料及簽名，準備 COS 郵寄帳單申請表。','form-total':'1','page-total':'共 1 頁，COS 申請表','name-hint':'填入 COS 的 Registered Owner Name。','mobile-label':'電話號碼 Mobile No.','mobile-hint':'填入 COS 客戶資料欄的 Mobile No.。','signature-hint':'簽名會放入 COS 表格的 Customer Signature / Company Stamp 欄。','preview-hint':'下載前請核對客戶資料、備註及簽名。','footer-task':'長者申請郵寄帳單 · COS','download-all':'下載 COS（1 頁 PDF）'});if(address)Object.assign(copy,{'task-number':'服務申請 / 04','task-title':'更改地址','task-description':'更新登記及郵寄帳單地址，準備 COS 申請表。','preview-hint':'下載前請核對客戶資料、新地址及簽名。','footer-task':'更改地址 · COS'});if(correction)Object.assign(copy,{'task-number':'服務申請 / 05','task-title':'錯名改正','task-description':'更正客戶名稱，同步準備 COS 及 MNP 表格。','name-hint':'填入 COS 客戶資料的 Registered Owner Name（錯誤名稱）。','mobile-label':'電話號碼 Mobile No.','mobile-hint':'同一號碼填入 COS 客戶資料及 MNP。','date-label':'MNP 轉台日期','date-hint':'此日期只填入 MNP，不填入 COS。','prepaid-label':'此號碼是否儲值卡？','preview-hint':'核對 COS 的錯誤及正確名稱，以及 MNP 的正確名稱、轉台安排及簽名。','footer-task':'錯名改正 · COS + MNP'});if(ownership)Object.assign(copy,{'task-number':'服務申請 / 06','task-title':'轉台轉名','task-description':'填寫原持有人及新持有人資料，準備 COS 及 MNP 表格。','name-hint':'原持有人資料會填入 COS 客戶資料及 MNP。','mobile-label':'電話號碼 Mobile No.','mobile-hint':'同一號碼填入 COS 客戶資料及 MNP。','date-label':'轉名生效 / 轉台日期','date-hint':'填入 COS Change of Ownership 及 MNP Requested Cut-over Time。','prepaid-label':'此號碼是否儲值卡？','signature-hint':'原持有人簽名用於 COS 轉讓人欄及 MNP；兩個簽名亦會並排放入 COS 最後的簽署欄。','preview-hint':'核對雙方資料、轉名及轉台日期，以及兩個簽名。MNP 使用原持有人資料及簽名。','footer-task':'轉台轉名 · COS + MNP'});if(broadband)Object.assign(copy,{'task-number':'服務申請 / 07','task-title':'寛頻工單更改','task-description':'選擇取消登記、修改安裝日期或生效日期，準備 COS 申請表。','mobile-label':'寛頻帳戶號碼','mobile-hint':'填入 COS 客戶資料的 Mobile No. 欄。','footer-task':'寛頻工單更改 · COS'});Object.entries(copy).forEach(([id,value])=>$('#'+id).textContent=value);
 $('#old-number-field').hidden=singleNumber;$('#oldNumber').disabled=singleNumber;$('#oldNumber').required=!singleNumber;$('#newNumber').setCustomValidity('');$('#mobile-field').classList.toggle('full',singleNumber);
 document.querySelectorAll('[data-cos-only]').forEach(el=>el.hidden=dateOnly);$('#number-arrow').hidden=singleNumber;$('#tab-cos').hidden=dateOnly;$('#separate-downloads').hidden=cosOnly||dateOnly;
 $('#owner-fields').hidden=!ownership;document.querySelectorAll('#owner-fields input').forEach(el=>el.disabled=!ownership);$('#transferee-pad').hidden=!ownership;$('#signature-title').textContent=ownership?'原號碼持有人簽署':'客戶簽名';$('#signature').setAttribute('aria-label',ownership?'原號碼持有人簽署':'客戶簽名區');$('#identity-label').textContent=ownership?'原號碼持有人證件號碼':'香港身份證 / 護照 / 商業登記號碼';$('#customer-name-label').textContent=ownership?'原號碼持有人名稱':correction?'錯誤名稱 Registered Owner Name':'客戶英文姓名 / 公司名稱';$('#name').placeholder=correction?'請輸入現有錯誤名稱':'Registered Owner Name / Name in English';$('#correction-fields').hidden=!correction;$('#correction-id-hint').hidden=!correction;document.querySelectorAll('#correction-fields input, #correction-fields select').forEach(el=>el.disabled=!correction);$('#address-fields').hidden=!address;document.querySelectorAll('#address-fields input, #address-fields select').forEach(el=>el.disabled=!address);$('#porting-fields').hidden=cosOnly;document.querySelectorAll('#porting-fields input, #porting-fields select').forEach(el=>el.disabled=cosOnly);$('#senior-remark').hidden=!senior;$('#recipient-fixed').hidden=cosOnly;$('#fee-note').hidden=task!=='cover';$('#tab-mnp').hidden=cosOnly;$('#tab-terms').hidden=cosOnly;$('#arrangement-title').textContent=broadband?'寛頻工單更改':address?'新登記及郵寄帳單地址':senior?'郵寄帳單申請':'轉台安排';$('#arrangement-subtitle').textContent=broadband?'Broadband work order changes':address?'New registered / billing address':senior?'Postal bill request':'Number portability details';$('#signature-instruction').textContent=cosOnly?'請核對申請內容，並由客戶本人簽署。':'請先閱讀右側 MNP 條款，並由客戶本人簽署。';
 $('#broadband-fields').hidden=!broadband;const account=$('#newNumber');account.type=broadband?'text':'tel';account.inputMode=broadband?'text':'numeric';account.pattern=broadband?'.*\\S.*':'[0-9]{8}';account.maxLength=broadband?40:8;account.placeholder=broadband?'請輸入寛頻帳戶號碼':'8 位數字';syncBroadband();
 selectedPage=dateOnly?'mnp':'cos';update();selectTab($('#tab-'+selectedPage));$('#status').textContent=ready?'草稿':'載入表格中';$('#error').textContent='';
}
document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>setTask(b.dataset.task));


const transfereeCanvas=$('#signature-transferee'),transfereeContext=transfereeCanvas.getContext('2d');let transfereePointer=null,transfereeStroke=null;
function drawTransferee(){const c=transfereeContext;c.clearRect(0,0,1000,300);c.strokeStyle='#162c39';c.lineWidth=3.5;c.lineCap='round';c.lineJoin='round';for(const stroke of transfereeStrokes){c.beginPath();stroke.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.stroke();}if(transfereeImage)engine.drawSignatureImage(c,transfereeImage,0,0,1000,300);$('#transferee-placeholder').hidden=!!transfereeImage||transfereeStrokes.some(s=>s.length>1);$('#undo-transferee').disabled=!transfereeImage&&transfereeStrokes.length===0;$('#clear-transferee').disabled=!transfereeImage&&transfereeStrokes.length===0;}
function transfereePoint(e){const r=transfereeCanvas.getBoundingClientRect();return{x:Math.max(0,Math.min(1000,(e.clientX-r.left)/r.width*1000)),y:Math.max(0,Math.min(300,(e.clientY-r.top)/r.height*300))};}
transfereeCanvas.addEventListener('pointerdown',e=>{if(transfereePointer!==null||e.button>0||transfereeImage||transfereeLoading)return;e.preventDefault();transfereePointer=e.pointerId;transfereeCanvas.setPointerCapture(e.pointerId);transfereeStroke=[transfereePoint(e)];transfereeStrokes.push(transfereeStroke);drawTransferee();});
transfereeCanvas.addEventListener('pointermove',e=>{if(e.pointerId!==transfereePointer||!transfereeStroke)return;e.preventDefault();transfereeStroke.push(transfereePoint(e));drawTransferee();});
function finishTransferee(e){if(e.pointerId!==transfereePointer)return;if(transfereeStroke?.length<2)transfereeStrokes.pop();transfereePointer=null;transfereeStroke=null;drawTransferee();changed();}
['pointerup','pointercancel','lostpointercapture'].forEach(event=>transfereeCanvas.addEventListener(event,finishTransferee));
$('#undo-transferee').onclick=()=>{transfereeUploadVersion++;transfereeLoading=false;if(transfereeImage){transfereeImage=null;$('#transferee-upload').value='';}else transfereeStrokes.pop();drawTransferee();changed();};$('#clear-transferee').onclick=()=>{transfereeUploadVersion++;transfereeLoading=false;transfereeImage=null;$('#transferee-upload').value='';transfereeStrokes=[];drawTransferee();changed();};drawTransferee();


async function uploadSignature(input,isTransferee){const file=input.files?.[0];if(!file)return;const version=isTransferee?++transfereeUploadVersion:++signatureUploadVersion;if(isTransferee)transfereeLoading=true;else signatureLoading=true;$('#error').textContent='';let url;
try{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('format');url=URL.createObjectURL(file);const image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url;});if(version!==(isTransferee?transfereeUploadVersion:signatureUploadVersion))return;if(!image.naturalWidth||!image.naturalHeight)throw new Error('empty');if(isTransferee){transfereeImage=image;transfereeStrokes=[];drawTransferee();}else{signatureImage=image;strokes=[];drawSignature();}changed();}
catch(e){if(version===(isTransferee?transfereeUploadVersion:signatureUploadVersion))$('#error').textContent='無法讀取簽名圖片，請選擇 PNG、JPG 或 WebP 圖片，或直接手寫簽署。';}
finally{if(url)URL.revokeObjectURL(url);if(version===(isTransferee?transfereeUploadVersion:signatureUploadVersion)){if(isTransferee)transfereeLoading=false;else signatureLoading=false;input.value='';}}}
$('#signature-upload').addEventListener('change',e=>uploadSignature(e.target,false));$('#transferee-upload').addEventListener('change',e=>uploadSignature(e.target,true));

function syncBroadband(){const enabled=task==='broadband',action=$('#broadbandAction').value,install=enabled&&action==='install',effective=enabled&&['install','effective'].includes(action);$('#broadbandAction').disabled=!enabled;$('#installation-field').hidden=!install;$('#installationDate').disabled=!install;$('#installationDate').required=install;$('#installation-time-field').hidden=!install;$('#installationTime').disabled=!install;$('#installationTime').required=install;$('#effective-field').hidden=!effective;$('#effectiveDate').disabled=!effective;$('#effectiveDate').required=effective;$('#broadband-remark').textContent=engine.broadbandRemark(data())||'請選擇更改項目。';}
['broadbandAction','installationDate','installationTime','effectiveDate'].forEach(id=>$('#'+id).addEventListener('input',syncBroadband));
syncBroadband();drawSignature();update();load();document.addEventListener('visibilitychange',()=>{if(!document.hidden)update();});setInterval(()=>{if($('#today').textContent!==engine.dateText(engine.hongKongToday()))update();},30000);
