/* Shared rendering for the live preview and all PDF downloads. Coordinates are A4 points. */
globalThis.FormEngine=(()=>{
const W=595.32,H=841.92,SCALE=3;
function hongKongToday(now=new Date()){const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Hong_Kong',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const get=t=>parts.find(p=>p.type===t).value;return `${get('year')}-${get('month')}-${get('day')}`;}
function dateText(iso,short=false){if(!iso)return '';const [y,m,d]=iso.split('-');return `${d}/${m}/${short?y.slice(-2):y}`;}
function mapping(data,today=hongKongToday()){return {cos:{name:data.name.trim(),identity:data.identity.trim(),mobile:['senior','address','name','owner','broadband'].includes(data.task)?data.newNumber:data.oldNumber,from:data.oldNumber,to:data.newNumber,commencement:data.task==='name'?'':data.commencement,today,handled:'Ray Ho',channel:'DPAC'},mnp:{name:(data.prepaid==='yes'?'PREPAID SIM ':'')+(data.task==='name'?data.correctName:data.name).trim(),mobile:data.newNumber,identity:data.identity.trim(),donor:data.donor.trim(),recipient:'CMHK',commencement:data.commencement,hours:data.hours,prepaid:data.prepaid,today}};}
function text(ctx,value,x,y,width,size=10){if(!value)return;ctx.fillStyle='#111';ctx.font=`${size}px Arial,sans-serif`;ctx.fillText(String(value),x,y,width);}
function line(ctx,x,y,x2,y2,width=1){ctx.strokeStyle='#111';ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();}
function tick(ctx,x,y){ctx.lineCap='round';line(ctx,x-2.8,y,x-.5,y+2.8,1.2);line(ctx,x-.5,y+2.8,x+4,y-3,1.2);}
function circle(ctx,x,y){ctx.strokeStyle='#111';ctx.lineWidth=.9;ctx.beginPath();ctx.ellipse(x,y,5.5,7,0,0,Math.PI*2);ctx.stroke();}
function splitDate(ctx,iso,x,y,step){if(!iso)return;const [yy,mm,dd]=iso.split('-');[dd,mm,yy.slice(-2)].forEach((v,i)=>text(ctx,v,x+i*step,y,15,10));}
function broadbandRemark(data){if(data.broadbandAction==='cancel')return '客戶要求取消登記及即時撤單';if(data.broadbandAction==='install')return `工單安裝修改 - 更改安裝日期: ${dateText(data.installationDate)} ${data.installationTime||''}; 生效日期: ${dateText(data.effectiveDate)}`;if(data.broadbandAction==='effective')return `工單安裝修改 - 更改生效日期: ${dateText(data.effectiveDate)}`;return '';}
function drawSignatureImage(ctx,image,x,y,w,h){const iw=image.naturalWidth||image.width,ih=image.naturalHeight||image.height;if(!iw||!ih)return;const scale=Math.min(w/iw,h/ih),dw=iw*scale,dh=ih*scale;ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.drawImage(image,x+(w-dw)/2,y+(h-dh)/2,dw,dh);ctx.restore();}
function signature(ctx,strokes,x,y,w,h){if(strokes?.image){drawSignatureImage(ctx,strokes.image,x,y,w,h);return;}const points=strokes.flat();if(!points.length)return;const xs=points.map(p=>p.x),ys=points.map(p=>p.y);const x0=Math.min(...xs),y0=Math.min(...ys),sw=Math.max(1,Math.max(...xs)-x0),sh=Math.max(1,Math.max(...ys)-y0);const scale=Math.min((w-4)/sw,(h-4)/sh);const ox=x+(w-sw*scale)/2,oy=y+(h-sh*scale)/2;ctx.save();ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.lineWidth=1;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#111';for(const stroke of strokes){if(stroke.length<2)continue;ctx.beginPath();stroke.forEach((p,i)=>{const px=ox+(p.x-x0)*scale,py=oy+(p.y-y0)*scale;i?ctx.lineTo(px,py):ctx.moveTo(px,py);});ctx.stroke();}ctx.restore();}
function render(kind,data,strokes,images,createCanvas,today=hongKongToday()){const canvas=createCanvas();canvas.width=Math.round(W*SCALE);canvas.height=Math.round(H*SCALE);const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(images[kind],0,0,canvas.width,canvas.height);ctx.scale(canvas.width/W,canvas.height/H);const v=mapping(data,today)[kind];if(data.signatureImage)strokes={image:data.signatureImage};const transferee=data.transfereeImage?{image:data.transfereeImage}:data.transfereeStrokes||[];if(kind==='cos'){
ctx.fillStyle='white';ctx.fillRect(490,29,68,18);
text(ctx,v.name,133,113,152,9);text(ctx,v.identity,409,113,144,10);text(ctx,v.mobile,133,132,151,10);
if(data.task==='broadband'){
if(data.broadbandAction){ctx.strokeStyle='#111';ctx.lineWidth=.6;ctx.strokeRect(47,717,11,11);tick(ctx,52.5,722.5);
if(data.broadbandAction==='cancel')ctx.drawImage(images.bbCancel,108,715,140,16);
else{ctx.drawImage(data.broadbandAction==='install'?images.bbInstall:images.bbEffective,108,715,170,16);text(ctx,dateText(data.broadbandAction==='install'?data.installationDate:data.effectiveDate),270,727,60,9);if(data.broadbandAction==='install'){text(ctx,data.installationTime,332,727,70,9);ctx.drawImage(images.bbEffectiveLabel,405,715,70,16);text(ctx,dateText(data.effectiveDate),480,727,65,9);}}}
}else if(data.task==='senior'){ctx.strokeStyle='#111';ctx.lineWidth=.6;ctx.strokeRect(47,717,11,11);tick(ctx,52.5,722.5);ctx.drawImage(images.seniorRemark,108,715,440,17);}else if(data.task==='address'){
ctx.strokeStyle='#111';ctx.lineWidth=.8;ctx.beginPath();ctx.ellipse(95,191,56,10,0,0,Math.PI*2);ctx.stroke();
text(ctx,data.room,157,199,59,10);text(ctx,data.floor,222,199,52,10);text(ctx,data.block,281,199,88,10);text(ctx,data.building,376,199,177,10);text(ctx,data.street,43,222,171,10);text(ctx,data.district,220,222,147,10);text(ctx,data.region,400,222,135,10);
}else if(data.task==='owner'){
text(ctx,data.ownerName,151,486,134,9);text(ctx,data.ownerIdentity,409,486,144,10);splitDate(ctx,v.commencement,440,505,47.5);signature(ctx,strokes,151,515,134,26);signature(ctx,transferee,407,515,146,26);
}else if(data.task==='name'){
text(ctx,data.correctName,123,179,114,9);text(ctx,data.sex,264,179,39,10);text(ctx,v.identity,423,179,131,10);
}else{
tick(ctx,52.5,575.5);text(ctx,v.from,168,586,43,9);text(ctx,v.to,265,586,42,9);splitDate(ctx,v.commencement,388,586,24);
line(ctx,503,577,531,577,1);line(ctx,503,585,531,585,1);
}
splitDate(ctx,v.today,438,763,48);text(ctx,v.handled,88,809,76,10);text(ctx,v.channel,213,809,75,10);if(data.task==='owner'){signature(ctx,strokes,169,736,63,28);signature(ctx,transferee,239,736,63,28);}else signature(ctx,strokes,169,736,134,28);
}else if(kind==='mnp'){
text(ctx,v.name,200,163,340,12);text(ctx,v.mobile,200,198,115,12);text(ctx,v.identity,240,245,305,12);text(ctx,v.donor,240,290,305,12);text(ctx,v.recipient,240,337,305,12);text(ctx,dateText(v.commencement),205,387,110,12);
if(v.hours==='night')tick(ctx,340.5,384.5);if(v.hours==='noon')tick(ctx,436.5,384.5);
if(v.prepaid==='yes'){tick(ctx,340.5,192.5);circle(ctx,502,192);}else if(v.prepaid==='no')circle(ctx,515.5,192);
text(ctx,dateText(v.today),416,700,130,12);signature(ctx,strokes,40,661,192,48);
}ctx.setTransform(1,0,0,1,0,0);return canvas;}
function pdf(canvases){const chunks=[],offsets=[0];let length=0;const add=s=>{const b=typeof s==='string'?Uint8Array.from(s,c=>c.charCodeAt(0)):s;chunks.push(b);length+=b.length;};const obj=(id,s)=>{offsets[id]=length;add(`${id} 0 obj\n${s}\nendobj\n`);};add('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n');obj(1,'<< /Type /Catalog /Pages 2 0 R >>');obj(2,`<< /Type /Pages /Kids [${canvases.map((_,i)=>`${3+i*3} 0 R`).join(' ')}] /Count ${canvases.length} >>`);canvases.forEach((c,i)=>{const id=3+i*3;obj(id,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /XObject << /Im0 ${id+1} 0 R >> >> /Contents ${id+2} 0 R >>`);const jpg=atob(c.toDataURL('image/jpeg',.97).split(',')[1]);offsets[id+1]=length;add(`${id+1} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${c.width} /Height ${c.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>\nstream\n`);add(jpg);add('\nendstream\nendobj\n');const content=`q\n${W} 0 0 ${H} 0 0 cm\n/Im0 Do\nQ\n`;obj(id+2,`<< /Length ${content.length} >>\nstream\n${content}endstream`);});const start=length,count=3+canvases.length*3;add(`xref\n0 ${count}\n0000000000 65535 f \n`);for(let i=1;i<count;i++)add(String(offsets[i]).padStart(10,'0')+' 00000 n \n');add(`trailer\n<< /Size ${count} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`);return new Blob(chunks,{type:'application/pdf'});}
function documentKinds(task,which='all'){if(['senior','address','broadband'].includes(task))return ['cos'];if(task==='date')return ['mnp','terms'];return which==='cos'?['cos']:which==='mnp'?['mnp','terms']:['cos','mnp','terms'];}
function downloadGroups(task,which,data){const kinds=documentKinds(task,which),prefix=task==='cover'?`${data.oldNumber} to ${data.newNumber}`:data.newNumber;return ['cos','mnp'].filter(kind=>kinds.includes(kind)).map(kind=>({filename:`${prefix} ${kind.toUpperCase()} Form.pdf`,kinds:kind==='cos'?['cos']:['mnp','terms']}));}
return {broadbandRemark,hongKongToday,dateText,mapping,render,pdf,documentKinds,downloadGroups,drawSignatureImage};})();
