const test=require('node:test'),assert=require('node:assert/strict');const handler=require('../api/gateway.js');const {hash,identity,sessionCookie}=require('../server/security.cjs');
Object.assign(process.env,{APP_ORIGIN:'https://tool.example',SUPABASE_URL:'https://project.supabase.co',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'secret',RATE_LIMIT_SECRET:'x'.repeat(40),SMS_ENABLED:'true'});
let active=true,rate=true,otpCalls=0,verified=true,recorded=[];
global.fetch=async(url,opts={})=>{let out=[];const u=new URL(url),body=opts.body?JSON.parse(opts.body):null;if(u.pathname.endsWith('tool_rate_limit'))out=rate;else if(u.pathname.endsWith('tool_members'))out=active?[{id:'member-1',email:'approved@example.com',phone:'+85291234567'}]:[];else if(u.pathname.endsWith('tool_sessions'))out=opts.method==='POST'?[]:[{member_id:'member-1'}];else if(u.pathname.endsWith('tool_audit')){recorded.push(body);out=[];}else if(u.pathname.endsWith('/otp')){otpCalls++;out={};}else if(u.pathname.endsWith('/verify')){if(!verified)return {ok:false};out={user:{email:'approved@example.com',phone:'85291234567'}};}else throw new Error('unexpected '+url);return {ok:true,status:200,json:async()=>out};};
async function request(url,{method='GET',body,cookie,origin='https://tool.example'}={}){const headers={},res={statusCode:200,setHeader(k,v){headers[k]=v},end(data){this.data=data}};await handler({url,method,body,headers:{origin,'content-type':'application/json',cookie:cookie||''},socket:{remoteAddress:'127.0.0.1'}},res);return {...res,headers};}
test('identity normalization, international numbers and cookie flags',()=>{assert.equal(identity({method:'email',identity:' A@Example.com '}).value,'a@example.com');assert.equal(identity({method:'sms',identity:'+852 9123 4567'}).value,'+85291234567');assert.throws(()=>identity({method:'sms',identity:'91234567'}));assert.match(sessionCookie('abc'),/HttpOnly; Secure; SameSite=Strict/);});
test('unauthenticated root redirects and protected resources never return bytes',async()=>{assert.equal((await request('/')).headers.Location,'/login');for(const p of ['/app.js','/template.png','/private/tool/app.js','/dist/index.html','/auth/session']){const r=await request(p);assert.equal(r.statusCode,401);assert.equal(r.headers['Cache-Control'],'private, no-store, max-age=0');}});
test('cross-origin POST rejected before provider use',async()=>{assert.equal((await request('/auth/send',{method:'POST',origin:'https://evil.example',body:{}})).statusCode,403);});
test('unapproved identity gets generic send response and no OTP',async()=>{active=false;const before=otpCalls;const r=await request('/auth/send',{method:'POST',body:{method:'email',identity:'unapproved@example.com'}});assert.equal(r.statusCode,200);assert.equal(otpCalls,before);active=true;});
test('rate limit blocks sending and verification',async()=>{rate=false;for(const p of ['/auth/send','/auth/verify'])assert.equal((await request(p,{method:'POST',body:{method:'email',identity:'approved@example.com',code:'123456'}})).statusCode,429);rate=true;});
test('verified email and SMS issue opaque cookies, never provider tokens',async()=>{for(const method of ['email','sms']){const r=await request('/auth/verify',{method:'POST',body:{method,identity:method==='email'?'approved@example.com':'+85291234567',code:'123456'}});assert.equal(r.statusCode,200);assert.match(r.headers['Set-Cookie'],/__Host-cmhk_session=[a-f0-9]{64}/);assert.equal(r.data,'{"ok":true}');}});
test('invalid code fails closed',async()=>{verified=false;assert.equal((await request('/auth/verify',{method:'POST',body:{method:'email',identity:'approved@example.com',code:'000000'}})).statusCode,401);verified=true;});
test('revocation denies existing session; traversal never exposes source',async()=>{active=false;const cookie='__Host-cmhk_session='+'a'.repeat(64);assert.equal((await request('/auth/session',{cookie})).statusCode,401);active=true;assert.equal((await request('/private/tool/app.js',{cookie})).statusCode,404);assert.equal((await request('/../schema.sql',{cookie})).statusCode,404);});
test('audit accepts only known task and never copies submitted personal data',async()=>{const cookie='__Host-cmhk_session='+'a'.repeat(64);await request('/auth/generate',{method:'POST',cookie,body:{task:'broadband',identity:'secret HKID',signature:'private'}});assert.deepEqual(recorded.at(-1),{member_id:'member-1',event:'generate_request',task:'broadband'});assert.equal((await request('/auth/generate',{method:'POST',cookie,body:{task:'unknown'}})).statusCode,400);});
test('missing configuration never falls back to unprotected static output',async()=>{const old=process.env.RATE_LIMIT_SECRET;delete process.env.RATE_LIMIT_SECRET;assert.equal((await request('/app.js')).statusCode,503);process.env.RATE_LIMIT_SECRET=old;});
test('logout removes session and clears secure cookie',async()=>{const r=await request('/auth/logout',{method:'POST',cookie:'__Host-cmhk_session='+'a'.repeat(64),body:{}});assert.equal(r.statusCode,200);assert.match(r.headers['Set-Cookie'],/Max-Age=0/);});
test('Vercel rewritten paths serve only allowed files after authentication',async()=>{const previous=process.cwd();process.chdir(require('node:path').join(__dirname,'..'));try{const r=await request('/api/gateway?__path=app.js',{cookie:'__Host-cmhk_session='+'a'.repeat(64)});assert.equal(r.statusCode,200);assert.match(r.data.toString(),/recordGeneration/);const login=await request('/api/gateway?__path=login');assert.equal(login.statusCode,200);assert.match(login.data.toString(),/Approved users only/);assert.equal((await request('/api/gateway?__path=app.js')).statusCode,401);}finally{process.chdir(previous);}});
